import re

with open('src/components/broker/BrokerCRMWorkspace.tsx', 'r') as f:
    content = f.read()

new_use_effect = """
  useEffect(() => {
    async function fetchCRMData() {
      setIsLoadingData(true);
      try {
        const { data: clientsData, error: clientsErr } = await supabase.from('clients').select('*');
        if (!clientsErr && clientsData) {
          setClients(clientsData.map(c => ({
            id: c.id,
            fullName: c.name,
            email: c.email || '',
            phone: c.phone || '',
            company: c.type === 'Corporate' ? c.name : 'Private Office',
            type: c.type || 'HNWI',
            countryCode: '+234',
            preferredAircraftClass: 'Heavy Jet',
            tailAvoidances: [],
            dietaryRestrictions: c.preferences ? Object.values(c.preferences) : [],
            petPolicy: 'Standard',
            securityDetails: 'None',
            assignedBroker: c.broker_id,
            totalFlightsBooked: 0,
            totalLifetimeSpendUsd: c.total_spend || 0,
            passportVault: []
          })));
        }

        const { data: proposalsData, error: propsErr } = await supabase.from('proposals').select('*');
        if (!propsErr && proposalsData) {
          setDeals(proposalsData.map(p => ({
            id: p.id,
            dealCode: p.id.substring(0, 8).toUpperCase(),
            clientId: p.broker_id,
            clientName: p.client_name,
            stage: p.status === 'DRAFT' ? 'Inquiry' : p.status === 'SENT' ? 'Quote Sent' : p.status === 'ACCEPTED' ? 'Contract Signed' : 'Inquiry',
            origin: p.flight_details?.origin || 'TBD',
            destination: p.flight_details?.destination || 'TBD',
            aircraftCategory: p.flight_details?.aircraft || 'Heavy Jet',
            targetDate: p.flight_details?.date || 'TBD',
            wholesaleCostUsd: (p.total_price || 0) * 0.9,
            brokerMarkupPercent: 10,
            totalValueUsd: p.total_price || 0,
            brokerCommissionUsd: (p.total_price || 0) * 0.1,
            assignedBroker: p.broker_id,
            lastUpdated: p.updated_at,
            missionCode: p.id.substring(0, 6).toUpperCase()
          })));
        }
        
        const { data: historyData, error: histErr } = await supabase.from('flight_history').select('*');
        if (!histErr && historyData) {
          setHistory(historyData.map(h => ({
            id: h.id,
            missionCode: h.id.substring(0, 6).toUpperCase(),
            clientName: 'Client',
            flightDate: h.date,
            route: h.route,
            aircraftModel: h.aircraft,
            wholesaleCostUsd: (h.amount || 0) * 0.9,
            brokerProfitUsd: (h.amount || 0) * 0.1,
            operatorName: 'Network Operator',
            operatorRating: 5,
            paymentRail: 'Providus NUBAN (NGN)',
            status: h.status === 'COMPLETED' ? 'Completed' : 'Scheduled',
            flightDuration: '4h 30m'
          })));
        }

        const { data: tasksData, error: tasksErr } = await supabase.from('tasks').select('*').order('due_date', { ascending: true });
        if (!tasksErr && tasksData) {
          setTasks(tasksData.map(t => ({
            id: t.id,
            title: t.title,
            clientName: '',
            dueDate: t.due_date ? new Date(t.due_date).toLocaleDateString() : 'Today',
            priority: 'High',
            category: t.type === 'Call' ? 'Follow Up' : 'Charter Prep',
            completed: t.status === 'completed',
            autoGenerated: true
          })));
        }
      } catch (err) {
        console.error("Error fetching CRM data:", err);
      } finally {
        setIsLoadingData(false);
      }
    }
    fetchCRMData();
  }, []);
"""

# We need to replace the entire useEffect that starts on line 420
regex = r"useEffect\(\(\) => \{\n\s*async function fetchCRMData\(\) \{.*?\},\s*\[\]\);"
content = re.sub(regex, new_use_effect.strip(), content, flags=re.DOTALL)

with open('src/components/broker/BrokerCRMWorkspace.tsx', 'w') as f:
    f.write(content)
