import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Users,
  Kanban,
  FileText,
  History,
  MessageSquare,
  TrendingUp,
  CheckSquare,
  Plane,
  ExternalLink,
  ShieldCheck,
  Search,
  Plus,
  Filter,
  ArrowRight,
  Phone,
  Mail,
  Building,
  Calendar,
  AlertCircle,
  Clock,
  ChevronRight,
  DollarSign,
  Download,
  Upload,
  Copy,
  Check,
  Sparkles,
  Lock,
  UserPlus,
  X,
  File,
  Shield,
  Eye,
  Send,
  Zap,
  Briefcase,
  Sliders,
  ChevronDown,
  Globe,
  Award,
  LogOut
} from 'lucide-react';
import { formatCurrency, formatToLocalDate, copyToClipboard } from '../../lib/utils';
import { WhiteLabelProposalBuilder } from './WhiteLabelProposalBuilder';

/* Types for CRM Core */
export interface ClientProfile {
  id: string;
  fullName: string;
  email: string;
  phone: string;
  company: string;
  type: 'HNWI' | 'Corporate' | 'Family Office' | 'VIP Royal';
  countryCode: string;
  preferredAircraftClass: string;
  tailAvoidances: string[];
  dietaryRestrictions: string[];
  petPolicy: string;
  securityDetails: string;
  assignedBroker: string;
  totalFlightsBooked: number;
  totalLifetimeSpendUsd: number;
  passportVault: {
    id: string;
    passengerName: string;
    passportNumber: string;
    nationality: string;
    expiryDate: string;
    status: 'Valid' | 'Expiring Soon' | 'Expired';
  }[];
}

export interface DealPipelineItem {
  id: string;
  dealCode: string;
  clientId: string;
  clientName: string;
  stage: 'Inquiry' | 'Quote Sent' | 'Proposal Viewed' | 'Contract Signed' | 'Commission Settled';
  origin: string;
  destination: string;
  aircraftCategory: string;
  targetDate: string;
  wholesaleCostUsd: number;
  brokerMarkupPercent: number;
  totalValueUsd: number;
  brokerCommissionUsd: number;
  assignedBroker: string;
  lastUpdated: string;
  missionCode?: string;
}

export interface FlightHistoryRecord {
  id: string;
  missionCode: string;
  clientName: string;
  flightDate: string;
  route: string;
  aircraftModel: string;
  wholesaleCostUsd: number;
  brokerProfitUsd: number;
  operatorName: string;
  operatorRating: number;
  paymentRail: 'Providus NUBAN (NGN)' | 'USDC Escrow (Solana/Base L2)';
  status: 'Completed' | 'In Flight' | 'Scheduled';
  flightDuration: string;
}

export interface CRMTask {
  id: string;
  title: string;
  clientName?: string;
  dueDate: string;
  priority: 'High' | 'Medium' | 'Normal';
  category: 'Follow Up' | 'Passport Alert' | 'Charter Prep' | 'Payment Check';
  completed: boolean;
  autoGenerated?: boolean;
}

export interface TeamMember {
  id: string;
  fullName: string;
  role: 'Head Broker' | 'Senior Broker' | 'Junior Broker' | 'Flight Coordinator';
  email: string;
  assignedDealsCount: number;
  closedVolumeUsd: number;
  commissionSplitPercent: number;
  avatarUrl?: string;
}

export interface AircraftDirectoryItem {
  id: string;
  tailNumber: string;
  model: string;
  category: 'Heavy Jet' | 'Ultra Long Range' | 'Super Midsize' | 'Light Jet' | 'VLJ';
  baseAirport: string;
  hourlyRateUsd: number;
  maxPassengers: number;
  rangeNm: number;
  operatorName: string;
  operatorAoc: string;
  argusRating: string;
  availableNow: boolean;
  photoUrl?: string;
}

/* Sample Initial Data for Immediate Interactive Richness */
export const INITIAL_CLIENTS: ClientProfile[] = [
  {
    id: 'cli-001',
    fullName: 'Chief Alani Adeleke',
    email: 'a.adeleke@adelekegroup.com',
    phone: '+234 803 112 8899',
    company: 'Adeleke Holdings Ltd',
    type: 'HNWI',
    countryCode: '+234',
    preferredAircraftClass: 'Heavy Jet (Challenger 650)',
    tailAvoidances: ['Avoid N-registered', 'No Legacy 600'],
    dietaryRestrictions: ['Halal', 'Dom Pérignon Vintage 2012', 'Gluten-Free'],
    petPolicy: '2 French Bulldogs in cabin, pet carpet covers required',
    securityDetails: 'Tarmac apron pickup required, 2 armed detail officers',
    assignedBroker: 'Tunde Bakare (Head Broker)',
    totalFlightsBooked: 14,
    totalLifetimeSpendUsd: 620000,
    passportVault: [
      {
        id: 'pass-1',
        passengerName: 'Alani Adeleke',
        passportNumber: 'A09823412',
        nationality: 'Nigerian',
        expiryDate: '2028-11-14',
        status: 'Valid'
      },
      {
        id: 'pass-2',
        passengerName: 'Folake Adeleke',
        passportNumber: 'A09823488',
        nationality: 'Nigerian',
        expiryDate: '2026-09-20',
        status: 'Expiring Soon'
      }
    ]
  },
  {
    id: 'cli-002',
    fullName: 'Zenith Executive Fleet',
    email: 'charter@zenithbank.com',
    phone: '+234 1 278 7000',
    company: 'Zenith Bank PLC',
    type: 'Corporate',
    countryCode: '+234',
    preferredAircraftClass: 'Ultra Long Range (Gulfstream G650ER)',
    tailAvoidances: ['No turboprops'],
    dietaryRestrictions: ['European Executive Lunch', 'Espresso machine required'],
    petPolicy: 'No pets on board',
    securityDetails: 'VIP Terminal Lounge clearance, Executive Protection protocol',
    assignedBroker: 'Amina Yusuf (Senior Broker)',
    totalFlightsBooked: 28,
    totalLifetimeSpendUsd: 1450000,
    passportVault: [
      {
        id: 'pass-3',
        passengerName: 'Dr. Ebenezer Onyeagwu',
        passportNumber: 'B88723910',
        nationality: 'Nigerian',
        expiryDate: '2029-04-10',
        status: 'Valid'
      }
    ]
  },
  {
    id: 'cli-003',
    fullName: 'Prince Abdulaziz Al-Saud',
    email: 'office@alsaud-royal.sa',
    phone: '+966 50 123 4567',
    company: 'Royal Arabian Investment',
    type: 'VIP Royal',
    countryCode: '+966',
    preferredAircraftClass: 'Ultra Long Range (Global 7500 / G650ER)',
    tailAvoidances: ['Strictly 2020+ manufacture year'],
    dietaryRestrictions: ['Strict Halal Gourmet', 'Zero Alcohol', 'Fresh Mango Juice'],
    petPolicy: 'Falcon perches for 2 falcons',
    securityDetails: 'Royal Guard Protocol, direct tarmac jetway access',
    assignedBroker: 'Tunde Bakare (Head Broker)',
    totalFlightsBooked: 8,
    totalLifetimeSpendUsd: 890000,
    passportVault: [
      {
        id: 'pass-4',
        passengerName: 'Abdulaziz Al-Saud',
        passportNumber: 'K99102938',
        nationality: 'Saudi Arabian',
        expiryDate: '2030-01-01',
        status: 'Valid'
      }
    ]
  }
];

export const INITIAL_DEALS: DealPipelineItem[] = [
  {
    id: 'deal-101',
    dealCode: 'DEAL-892',
    clientId: 'cli-001',
    clientName: 'Chief Alani Adeleke',
    stage: 'Proposal Viewed',
    origin: 'Lagos (LOS)',
    destination: 'London Biggin Hill (EGKB)',
    aircraftCategory: 'Heavy Jet (Challenger 650)',
    targetDate: '2026-08-25',
    wholesaleCostUsd: 110000,
    brokerMarkupPercent: 15,
    totalValueUsd: 126500,
    brokerCommissionUsd: 16500,
    assignedBroker: 'Tunde Bakare',
    lastUpdated: '2 hours ago',
    missionCode: '15D-7F9E'
  },
  {
    id: 'deal-102',
    dealCode: 'DEAL-893',
    clientId: 'cli-002',
    clientName: 'Zenith Executive Fleet',
    stage: 'Inquiry',
    origin: 'Abuja (ABV)',
    destination: 'Geneva (LSGG)',
    aircraftCategory: 'Ultra Long Range (Gulfstream G650ER)',
    targetDate: '2026-09-02',
    wholesaleCostUsd: 145000,
    brokerMarkupPercent: 12,
    totalValueUsd: 162400,
    brokerCommissionUsd: 17400,
    assignedBroker: 'Amina Yusuf',
    lastUpdated: '4 hours ago',
    missionCode: '15D-802'
  },
  {
    id: 'deal-103',
    dealCode: 'DEAL-894',
    clientId: 'cli-003',
    clientName: 'Prince Abdulaziz Al-Saud',
    stage: 'Contract Signed',
    origin: 'Riyadh (RUH)',
    destination: 'Nice Côte d\'Azur (NCE)',
    aircraftCategory: 'Ultra Long Range (Global 7500)',
    targetDate: '2026-08-18',
    wholesaleCostUsd: 165000,
    brokerMarkupPercent: 15,
    totalValueUsd: 189750,
    brokerCommissionUsd: 24750,
    assignedBroker: 'Tunde Bakare',
    lastUpdated: '1 day ago',
    missionCode: '15D-910'
  },
  {
    id: 'deal-104',
    dealCode: 'DEAL-895',
    clientId: 'cli-001',
    clientName: 'Chief Alani Adeleke',
    stage: 'Commission Settled',
    origin: 'Lagos (LOS)',
    destination: 'Port Harcourt (PHC)',
    aircraftCategory: 'Super Midsize (Hawker 900XP)',
    targetDate: '2026-08-01',
    wholesaleCostUsd: 18500,
    brokerMarkupPercent: 15,
    totalValueUsd: 21275,
    brokerCommissionUsd: 2775,
    assignedBroker: 'Tunde Bakare',
    lastUpdated: '3 days ago',
    missionCode: '15D-654'
  }
];

export const INITIAL_FLIGHT_HISTORY: FlightHistoryRecord[] = [
  {
    id: 'fl-01',
    missionCode: '15D-654',
    clientName: 'Chief Alani Adeleke',
    flightDate: '2026-08-01',
    route: 'LOS ✈ PHC',
    aircraftModel: 'Hawker 900XP (5N-BKL)',
    wholesaleCostUsd: 18500,
    brokerProfitUsd: 2775,
    operatorName: 'Air Peace Executive (AOC #AP-2024)',
    operatorRating: 5.0,
    paymentRail: 'Providus NUBAN (NGN)',
    status: 'Completed',
    flightDuration: '1h 10m'
  },
  {
    id: 'fl-02',
    missionCode: '15D-512',
    clientName: 'Zenith Executive Fleet',
    flightDate: '2026-07-20',
    route: 'ABV ✈ LOS ✈ ABV',
    aircraftModel: 'Challenger 605 (5N-ZNT)',
    wholesaleCostUsd: 34000,
    brokerProfitUsd: 4080,
    operatorName: 'Max Air Charter (AOC #MA-044)',
    operatorRating: 4.9,
    paymentRail: 'Providus NUBAN (NGN)',
    status: 'Completed',
    flightDuration: '2h 20m'
  },
  {
    id: 'fl-03',
    missionCode: '15D-409',
    clientName: 'Prince Abdulaziz Al-Saud',
    flightDate: '2026-07-10',
    route: 'RUH ✈ LHR',
    aircraftModel: 'Gulfstream G650ER (HZ-A1)',
    wholesaleCostUsd: 155000,
    brokerProfitUsd: 23250,
    operatorName: 'ExecuJet Middle East (AOC #OM-982)',
    operatorRating: 5.0,
    paymentRail: 'USDC Escrow (Solana/Base L2)',
    status: 'Completed',
    flightDuration: '6h 45m'
  }
];

export const INITIAL_TASKS: CRMTask[] = [
  {
    id: 'task-1',
    title: 'Follow up with Chief Adeleke on London Challenger quote',
    clientName: 'Chief Alani Adeleke',
    dueDate: 'Today',
    priority: 'High',
    category: 'Follow Up',
    completed: false,
    autoGenerated: true
  },
  {
    id: 'task-2',
    title: 'Passport renewal reminder for Folake Adeleke (Expires in 38 days)',
    clientName: 'Chief Alani Adeleke',
    dueDate: 'Tomorrow',
    priority: 'Medium',
    category: 'Passport Alert',
    completed: false,
    autoGenerated: true
  },
  {
    id: 'task-3',
    title: 'Confirm Geneva landing permit & VIP lounge with Zenith Bank',
    clientName: 'Zenith Executive Fleet',
    dueDate: '2026-08-15',
    priority: 'High',
    category: 'Charter Prep',
    completed: false
  },
  {
    id: 'task-4',
    title: 'Verify USDC Escrow release for Prince Abdulaziz Nice mission',
    clientName: 'Prince Abdulaziz Al-Saud',
    dueDate: '2026-08-17',
    priority: 'Normal',
    category: 'Payment Check',
    completed: false
  }
];

export const INITIAL_AIRCRAFT_DIRECTORY: AircraftDirectoryItem[] = [
  {
    id: 'air-1',
    tailNumber: '5N-BKL',
    model: 'Hawker 900XP',
    category: 'Super Midsize',
    baseAirport: 'Lagos Murtala Muhammed (DNMM)',
    hourlyRateUsd: 4800,
    maxPassengers: 8,
    rangeNm: 2800,
    operatorName: 'Air Peace Executive',
    operatorAoc: 'AOC/NG/089',
    argusRating: 'ARG/US Platinum',
    availableNow: true
  },
  {
    id: 'air-2',
    tailNumber: '5N-ZNT',
    model: 'Challenger 650',
    category: 'Heavy Jet',
    baseAirport: 'Abuja Nnamdi Azikiwe (DNAA)',
    hourlyRateUsd: 7900,
    maxPassengers: 12,
    rangeNm: 4000,
    operatorName: 'Max Air Charter',
    operatorAoc: 'AOC/NG/044',
    argusRating: 'IS-BAO Stage 3',
    availableNow: true
  },
  {
    id: 'air-3',
    tailNumber: 'HZ-A1',
    model: 'Gulfstream G650ER',
    category: 'Ultra Long Range',
    baseAirport: 'Dubai Al Maktoum (OMDW)',
    hourlyRateUsd: 13500,
    maxPassengers: 16,
    rangeNm: 7500,
    operatorName: 'ExecuJet Middle East',
    operatorAoc: 'AOC/UAE/102',
    argusRating: 'ARG/US Platinum',
    availableNow: true
  },
  {
    id: 'air-4',
    tailNumber: 'G-XLSB',
    model: 'Citation XLS+',
    category: 'Super Midsize',
    baseAirport: 'London Farnborough (EGLF)',
    hourlyRateUsd: 4200,
    maxPassengers: 9,
    rangeNm: 2100,
    operatorName: 'Gama Aviation UK',
    operatorAoc: 'AOC/UK/771',
    argusRating: 'ARG/US Gold+',
    availableNow: true
  }
];

export const INITIAL_TEAM_MEMBERS: TeamMember[] = [
  {
    id: 'tm-1',
    fullName: 'Tunde Bakare',
    role: 'Head Broker',
    email: 'tunde@15dwings.com.ng',
    assignedDealsCount: 5,
    closedVolumeUsd: 1250000,
    commissionSplitPercent: 70
  },
  {
    id: 'tm-2',
    fullName: 'Amina Yusuf',
    role: 'Senior Broker',
    email: 'amina@15dwings.com.ng',
    assignedDealsCount: 3,
    closedVolumeUsd: 680000,
    commissionSplitPercent: 50
  },
  {
    id: 'tm-3',
    fullName: 'Chidi Okonkwo',
    role: 'Junior Broker',
    email: 'chidi@15dwings.com.ng',
    assignedDealsCount: 2,
    closedVolumeUsd: 210000,
    commissionSplitPercent: 35
  }
];

interface BrokerCRMWorkspaceProps {
  missionId?: string;
  brokerCompanyName?: string;
  onIssueLiveCodeRequest?: (missionCode: string) => void;
  onLaunchVipSession?: (missionCode: string) => void;
  onOpenProposalBuilder?: (deal: DealPipelineItem) => void;
  hasVerifiedOperator?: boolean;
  onRequireOperator?: () => void;
  onSignOut?: () => void;
  onBookFlight?: () => void;
}

export const BrokerCRMWorkspace: React.FC<BrokerCRMWorkspaceProps> = ({
  missionId = '15D-001',
  brokerCompanyName = '15D Executive Aviation Brokerage',
  onIssueLiveCodeRequest,
  onLaunchVipSession,
  onOpenProposalBuilder,
  hasVerifiedOperator = false,
  onRequireOperator,
  onSignOut,
  onBookFlight
}) => {
  const [activeSubTab, setActiveSubTab] = useState<
    'pipeline' | 'clients' | 'proposals' | 'history' | 'analytics' | 'messaging' | 'tasks' | 'directory' | 'team'
  >('pipeline');

  /* State for Client Management */
  const [clients, setClients] = useState<ClientProfile[]>(INITIAL_CLIENTS);
  const [selectedClient, setSelectedClient] = useState<ClientProfile | null>(null);
  const [clientSearch, setClientSearch] = useState('');
  const [showAddClientModal, setShowAddClientModal] = useState(false);
  const [newClientName, setNewClientName] = useState('');
  const [newClientEmail, setNewClientEmail] = useState('');
  const [newClientPhone, setNewClientPhone] = useState('');
  const [newClientCompany, setNewClientCompany] = useState('');
  const [newClientType, setNewClientType] = useState<ClientProfile['type']>('HNWI');

  /* State for Pipeline Kanban */
  const [deals, setDeals] = useState<DealPipelineItem[]>(INITIAL_DEALS);
  const [selectedDeal, setSelectedDeal] = useState<DealPipelineItem | null>(null);
  const [showAddDealModal, setShowAddDealModal] = useState(false);
  const [newDealClient, setNewDealClient] = useState(INITIAL_CLIENTS[0].id);
  const [newDealOrigin, setNewDealOrigin] = useState('LOS');
  const [newDealDest, setNewDealDest] = useState('LHR');
  const [newDealAircraft, setNewDealAircraft] = useState('Heavy Jet (Challenger 650)');
  const [newDealCost, setNewDealCost] = useState(95000);

  /* State for Tasks */
  const [tasks, setTasks] = useState<CRMTask[]>(INITIAL_TASKS);
  const [newTaskTitle, setNewTaskTitle] = useState('');

  /* State for Messages */
  const [chatMessages, setChatMessages] = useState([
    { id: '1', sender: 'Chief Adeleke', text: 'Tunde, is the Challenger 650 confirmed for my August 25th flight to London?', time: '10:14 AM', isClient: true },
    { id: '2', sender: 'Tunde Bakare (Broker)', text: 'Yes Chief, aircraft tail 5N-ZNT is locked. Catering includes your Dom Pérignon 2012 request.', time: '10:18 AM', isClient: false },
    { id: '3', sender: 'Chief Adeleke', text: 'Excellent. Please send the passenger manifest link to my PA.', time: '10:22 AM', isClient: true }
  ]);
  const [newMessageInput, setNewMessageInput] = useState('');

  /* State for Copy Toast */
  const [copiedLink, setCopiedLink] = useState<string | null>(null);

  const handleCopyText = async (text: string, label: string) => {
    await copyToClipboard(text);
    setCopiedLink(label);
    setTimeout(() => setCopiedLink(null), 3000);
  };

  /* Move Deal Stage */
  const handleAdvanceStage = (dealId: string, nextStage: DealPipelineItem['stage']) => {
    setDeals(prev =>
      prev.map(d => (d.id === dealId ? { ...d, stage: nextStage, lastUpdated: 'Just now' } : d))
    );
  };

  /* Add Client */
  const handleCreateClient = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newClientName) return;
    const newCli: ClientProfile = {
      id: `cli-${Date.now()}`,
      fullName: newClientName,
      email: newClientEmail || 'client@vipavia.com',
      phone: newClientPhone || '+234 800 000 0000',
      company: newClientCompany || 'Private Office',
      type: newClientType,
      countryCode: '+234',
      preferredAircraftClass: 'Heavy Jet',
      tailAvoidances: [],
      dietaryRestrictions: ['Executive Catering'],
      petPolicy: 'Standard',
      securityDetails: 'VIP Protocol',
      assignedBroker: 'Tunde Bakare',
      totalFlightsBooked: 0,
      totalLifetimeSpendUsd: 0,
      passportVault: []
    };
    setClients(prev => [newCli, ...prev]);
    setShowAddClientModal(false);
    setNewClientName('');
    setNewClientEmail('');
    setNewClientPhone('');
    setNewClientCompany('');
  };

  /* Add Deal */
  const handleCreateDeal = (e: React.FormEvent) => {
    e.preventDefault();
    const cli = clients.find(c => c.id === newDealClient) || clients[0];
    const markup = 15;
    const totalVal = Math.round(newDealCost * (1 + markup / 100));
    const comm = totalVal - newDealCost;
    const newD: DealPipelineItem = {
      id: `deal-${Date.now()}`,
      dealCode: `DEAL-${Math.floor(800 + Math.random() * 199)}`,
      clientId: cli.id,
      clientName: cli.fullName,
      stage: 'Inquiry',
      origin: newDealOrigin,
      destination: newDealDest,
      aircraftCategory: newDealAircraft,
      targetDate: formatToLocalDate(new Date().toISOString()),
      wholesaleCostUsd: newDealCost,
      brokerMarkupPercent: markup,
      totalValueUsd: totalVal,
      brokerCommissionUsd: comm,
      assignedBroker: 'Tunde Bakare',
      lastUpdated: 'Just now',
      missionCode: `15D-${Math.floor(100 + Math.random() * 899)}`
    };
    setDeals(prev => [newD, ...prev]);
    setShowAddDealModal(false);
  };

  /* Add Task */
  const handleAddTask = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newTaskTitle) return;
    const task: CRMTask = {
      id: `task-${Date.now()}`,
      title: newTaskTitle,
      dueDate: 'Today',
      priority: 'High',
      category: 'Follow Up',
      completed: false
    };
    setTasks(prev => [task, ...prev]);
    setNewTaskTitle('');
  };

  const handleSendMessage = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newMessageInput.trim()) return;
    setChatMessages(prev => [
      ...prev,
      {
        id: `msg-${Date.now()}`,
        sender: 'Tunde Bakare (Broker)',
        text: newMessageInput,
        time: 'Just now',
        isClient: false
      }
    ]);
    setNewMessageInput('');
  };

  /* Filtered Clients */
  const filteredClients = clients.filter(
    c =>
      c.fullName.toLowerCase().includes(clientSearch.toLowerCase()) ||
      c.company.toLowerCase().includes(clientSearch.toLowerCase()) ||
      c.email.toLowerCase().includes(clientSearch.toLowerCase())
  );

  /* Total Stats Calculation */
  const totalClosedVolume = deals
    .filter(d => d.stage === 'Commission Settled' || d.stage === 'Contract Signed')
    .reduce((acc, d) => acc + d.totalValueUsd, 0);

  const totalCommissions = deals
    .filter(d => d.stage === 'Commission Settled' || d.stage === 'Contract Signed')
    .reduce((acc, d) => acc + d.brokerCommissionUsd, 0);

  return (
    <div className="w-full text-left font-sans space-y-6">
      {/* CRM Navigation Bar & Quick Actions */}
      <div className="p-4 md:p-6 rounded-[2rem] border border-purple-200/90 bg-white/95 backdrop-blur-xl shadow-[0_15px_40px_-10px_rgba(100,50,200,0.08)] relative overflow-hidden">
        <div className="flex flex-col xl:flex-row xl:items-center justify-between gap-4 pb-4 border-b border-purple-200">
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <span className="w-2.5 h-2.5 rounded-full bg-purple-600 animate-ping" />
              <span className="font-sync uppercase text-[10px] text-purple-700 tracking-[0.3em] font-bold">
                WHITE-LABEL FLIGHT BROKER CRM
              </span>
            </div>
            <h2 className="font-sync uppercase text-xl md:text-2xl font-bold tracking-wider text-gray-950 flex flex-wrap items-center gap-3">
              <span>BROKER CONTROL CRM</span>
            </h2>
            <p className="text-xs text-gray-700 font-normal">
              Full client pipeline, HNWI preferences, white-label quotes, and one-click execution bridge.
            </p>
          </div>

          <div className="flex flex-wrap items-center gap-2 sm:gap-3">
            <button 
              onClick={() => {
                if (!hasVerifiedOperator && onRequireOperator) {
                  onRequireOperator();
                } else if (onBookFlight) {
                  onBookFlight();
                } else {
                  window.open("https://fly.15dwings.com.ng", "_blank");
                }
              }} 
              className="flex items-center justify-center gap-2 px-4 py-2 bg-purple-600 hover:bg-purple-700 text-white rounded-xl text-[10px] font-bold font-sync uppercase transition-all shadow-md cursor-pointer"
            >
              <Plane className="w-3.5 h-3.5" />
              <span>BOOK FLIGHT</span>
            </button>

            {onSignOut && (
              <button
                onClick={onSignOut}
                className="flex items-center justify-center gap-2 px-4 py-2 bg-white hover:bg-red-50 border border-gray-200 hover:border-red-300 text-gray-800 hover:text-red-600 rounded-xl text-[10px] font-bold font-sync uppercase transition-all cursor-pointer shadow-sm"
              >
                <LogOut className="w-3.5 h-3.5" />
                <span>SIGN OUT</span>
              </button>
            )}
            <button
              onClick={() => setShowAddDealModal(true)}
              className="px-4 py-2.5 rounded-xl bg-purple-600 hover:bg-purple-700 text-white font-sync uppercase text-[10px] tracking-widest font-bold transition-all shadow-md flex items-center gap-2 cursor-pointer active:scale-95"
            >
              <Plus className="w-4 h-4" />
              <span>NEW DEAL INQUIRY</span>
            </button>

            <button
              onClick={() => setShowAddClientModal(true)}
              className="px-4 py-2.5 rounded-xl bg-purple-50 hover:bg-purple-100 text-purple-950 border border-purple-200 font-sync uppercase text-[10px] tracking-widest font-bold transition-all flex items-center gap-2 cursor-pointer active:scale-95 shadow-sm"
            >
              <UserPlus className="w-4 h-4 text-purple-600" />
              <span>ADD HNWI CLIENT</span>
            </button>
          </div>
        </div>

        {/* 10 Essential CRM Tab Switches */}
        <div className="flex items-center gap-1.5 overflow-x-auto pt-4 scrollbar-none">
          <button
            onClick={() => setActiveSubTab('pipeline')}
            className={`px-3.5 py-2 rounded-xl text-[10px] font-sync uppercase tracking-wider transition-all flex items-center gap-2 whitespace-nowrap cursor-pointer ${
              activeSubTab === 'pipeline'
                ? 'bg-purple-600 text-white font-bold shadow-md'
                : 'text-gray-700 hover:text-gray-950 hover:bg-purple-50 font-medium'
            }`}
          >
            <Kanban className="w-3.5 h-3.5" />
            <span>SALES PIPELINE</span>
            <span className={`ml-1 px-1.5 py-0.5 rounded-md text-[9px] font-mono ${
              activeSubTab === 'pipeline' ? 'bg-white/25 text-white' : 'bg-purple-100 text-purple-900'
            }`}>
              {deals.length}
            </span>
          </button>

          <button
            onClick={() => setActiveSubTab('clients')}
            className={`px-3.5 py-2 rounded-xl text-[10px] font-sync uppercase tracking-wider transition-all flex items-center gap-2 whitespace-nowrap cursor-pointer ${
              activeSubTab === 'clients'
                ? 'bg-purple-600 text-white font-bold shadow-md'
                : 'text-gray-700 hover:text-gray-950 hover:bg-purple-50 font-medium'
            }`}
          >
            <Users className="w-3.5 h-3.5" />
            <span>HNWI CLIENTS</span>
            <span className={`ml-1 px-1.5 py-0.5 rounded-md text-[9px] font-mono ${
              activeSubTab === 'clients' ? 'bg-white/25 text-white' : 'bg-purple-100 text-purple-900'
            }`}>
              {clients.length}
            </span>
          </button>

          <button
            onClick={() => setActiveSubTab('proposals')}
            className={`px-3.5 py-2 rounded-xl text-[10px] font-sync uppercase tracking-wider transition-all flex items-center gap-2 whitespace-nowrap cursor-pointer ${
              activeSubTab === 'proposals'
                ? 'bg-purple-600 text-white font-bold shadow-md'
                : 'text-gray-700 hover:text-gray-950 hover:bg-purple-50 font-medium'
            }`}
          >
            <FileText className="w-3.5 h-3.5" />
            <span>PROPOSAL BUILDER</span>
          </button>

          <button
            onClick={() => setActiveSubTab('history')}
            className={`px-3.5 py-2 rounded-xl text-[10px] font-sync uppercase tracking-wider transition-all flex items-center gap-2 whitespace-nowrap cursor-pointer ${
              activeSubTab === 'history'
                ? 'bg-purple-600 text-white font-bold shadow-md'
                : 'text-gray-700 hover:text-gray-950 hover:bg-purple-50 font-medium'
            }`}
          >
            <History className="w-3.5 h-3.5" />
            <span>TRIP LOGS</span>
          </button>

          <button
            onClick={() => setActiveSubTab('analytics')}
            className={`px-3.5 py-2 rounded-xl text-[10px] font-sync uppercase tracking-wider transition-all flex items-center gap-2 whitespace-nowrap cursor-pointer ${
              activeSubTab === 'analytics'
                ? 'bg-purple-600 text-white font-bold shadow-md'
                : 'text-gray-700 hover:text-gray-950 hover:bg-purple-50 font-medium'
            }`}
          >
            <TrendingUp className="w-3.5 h-3.5" />
            <span>REVENUE ANALYTICS</span>
          </button>

          <button
            onClick={() => setActiveSubTab('messaging')}
            className={`px-3.5 py-2 rounded-xl text-[10px] font-sync uppercase tracking-wider transition-all flex items-center gap-2 whitespace-nowrap cursor-pointer ${
              activeSubTab === 'messaging'
                ? 'bg-purple-600 text-white font-bold shadow-md'
                : 'text-gray-700 hover:text-gray-950 hover:bg-purple-50 font-medium'
            }`}
          >
            <MessageSquare className="w-3.5 h-3.5" />
            <span>CLIENT MESSAGING</span>
          </button>

          <button
            onClick={() => setActiveSubTab('tasks')}
            className={`px-3.5 py-2 rounded-xl text-[10px] font-sync uppercase tracking-wider transition-all flex items-center gap-2 whitespace-nowrap cursor-pointer ${
              activeSubTab === 'tasks'
                ? 'bg-purple-600 text-white font-bold shadow-md'
                : 'text-gray-700 hover:text-gray-950 hover:bg-purple-50 font-medium'
            }`}
          >
            <CheckSquare className="w-3.5 h-3.5" />
            <span>TASKS & ALERTS</span>
            <span className={`ml-1 px-1.5 py-0.5 rounded-md text-[9px] font-mono ${
              activeSubTab === 'tasks' ? 'bg-amber-400 text-amber-950 font-bold' : 'bg-amber-100 text-amber-900 font-bold'
            }`}>
              {tasks.filter(t => !t.completed).length}
            </span>
          </button>

          <button
            onClick={() => setActiveSubTab('directory')}
            className={`px-3.5 py-2 rounded-xl text-[10px] font-sync uppercase tracking-wider transition-all flex items-center gap-2 whitespace-nowrap cursor-pointer ${
              activeSubTab === 'directory'
                ? 'bg-purple-600 text-white font-bold shadow-md'
                : 'text-gray-700 hover:text-gray-950 hover:bg-purple-50 font-medium'
            }`}
          >
            <Plane className="w-3.5 h-3.5" />
            <span>FLEET DIRECTORY</span>
          </button>

          <button
            onClick={() => setActiveSubTab('team')}
            className={`px-3.5 py-2 rounded-xl text-[10px] font-sync uppercase tracking-wider transition-all flex items-center gap-2 whitespace-nowrap cursor-pointer ${
              activeSubTab === 'team'
                ? 'bg-purple-600 text-white font-bold shadow-md'
                : 'text-gray-700 hover:text-gray-950 hover:bg-purple-50 font-medium'
            }`}
          >
            <Briefcase className="w-3.5 h-3.5" />
            <span>TEAM ACCOUNTS</span>
          </button>
        </div>
      </div>

      {/* Copy Toast Alert */}
      <AnimatePresence>
        {copiedLink && (
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: 10 }}
            className="fixed bottom-6 right-6 z-50 px-4 py-3 bg-emerald-500 text-black font-space lowercase text-[11px] font-bold tracking-widest rounded-xl shadow-2xl flex items-center gap-2 lowercase"
          >
            <Check className="w-4 h-4" />
            <span>{copiedLink}</span>
          </motion.div>
        )}
      </AnimatePresence>

      {/* SUB-TAB 1: VISUAL SALES PIPELINE (KANBAN) */}
      {activeSubTab === 'pipeline' && (
        <div className="space-y-6">
          <div className="grid grid-cols-1 md:grid-cols-5 gap-4">
            {(
              [
                'Inquiry',
                'Quote Sent',
                'Proposal Viewed',
                'Contract Signed',
                'Commission Settled'
              ] as DealPipelineItem['stage'][]
            ).map((stage, stageIdx) => {
              const stageDeals = deals.filter(d => d.stage === stage);
              const stageTotal = stageDeals.reduce((acc, d) => acc + d.totalValueUsd, 0);

              return (
                <div
                  key={stage}
                  className="p-4 rounded-2xl border border-purple-200 bg-white/80 backdrop-blur-md backdrop-blur-[10px] space-y-3 flex flex-col justify-between"
                >
                  <div className="space-y-1 pb-3 border-b border-purple-200">
                    <div className="flex justify-between items-center">
                      <span className="font-space lowercase text-[10px] text-purple-600 tracking-widest font-bold lowercase">
                        STAGE 0{stageIdx + 1}
                      </span>
                      <span className="px-2 py-0.5 rounded-full bg-purple-100 text-[9px] font-mono text-gray-700">
                        {stageDeals.length}
                      </span>
                    </div>
                    <h3 className="font-space lowercase text-xs font-bold text-gray-900 tracking-wider lowercase">
                      {stage}
                    </h3>
                    <p className="text-[10px] text-emerald-400 font-mono font-semibold">
                      {formatCurrency(stageTotal, 'USD')}
                    </p>
                  </div>

                  <div className="space-y-3 min-h-[320px]">
                    {stageDeals.length === 0 ? (
                      <div className="p-4 rounded-xl border border-dashed border-purple-200 text-center text-gray-500 text-[10px] font-space lowercase lowercase tracking-widest">
                        NO DEALS IN THIS STAGE
                      </div>
                    ) : (
                      stageDeals.map(deal => (
                        <div
                          key={deal.id}
                          className="p-3.5 rounded-xl border border-purple-200 bg-purple-50 hover:border-purple-500/50 transition-all space-y-2.5 shadow-md relative group text-left"
                        >
                          <div className="flex justify-between items-start">
                            <span className="px-2 py-0.5 rounded bg-purple-600/20 text-purple-600 text-[9px] font-mono font-bold tracking-wider">
                              {deal.dealCode}
                            </span>
                            <span className="text-[9px] text-gray-600 font-mono">
                              {deal.lastUpdated}
                            </span>
                          </div>

                          <div>
                            <h4 className="font-space lowercase lowercase text-xs font-bold text-gray-900">
                              {deal.clientName}
                            </h4>
                            <p className="text-[10px] text-gray-700 font-mono flex items-center gap-1.5 pt-0.5">
                              <Plane className="w-3 h-3 text-purple-600" />
                              <span>{deal.origin} ➔ {deal.destination}</span>
                            </p>
                          </div>

                          <div className="p-2 rounded-lg bg-white/80 backdrop-blur-md border border-purple-100 space-y-1">
                            <div className="flex justify-between text-[10px]">
                              <span className="text-gray-600">Aircraft:</span>
                              <span className="text-gray-900 font-medium">{deal.aircraftCategory.split(' ')[0]}</span>
                            </div>
                            <div className="flex justify-between text-[10px]">
                              <span className="text-gray-600">Client Total:</span>
                              <span className="text-emerald-400 font-bold font-mono">
                                {formatCurrency(deal.totalValueUsd, 'USD')}
                              </span>
                            </div>
                            <div className="flex justify-between text-[10px]">
                              <span className="text-gray-600">Broker Margin:</span>
                              <span className="text-purple-600 font-bold font-mono">
                                +{formatCurrency(deal.brokerCommissionUsd, 'USD')} ({deal.brokerMarkupPercent}%)
                              </span>
                            </div>
                          </div>

                          <div className="pt-2 flex flex-col gap-1.5 border-t border-purple-200">

                          {/* Broker-to-Principal Communication Timeline */}
                          <div className="pt-3 border-t border-purple-200 space-y-2">
                            <h5 className="text-[10px] text-gray-600 font-space lowercase lowercase font-bold tracking-wider mb-2">Communication Timeline</h5>
                            <div className="space-y-1.5 border-l border-purple-500/30 pl-2 ml-1">
                                <div className="text-[9px] text-gray-700 font-mono">
                                    <span className="text-emerald-400">●</span> {deal.lastUpdated} - Proposal Sent to Principal
                                </div>
                                <div className="text-[9px] text-gray-700 font-mono">
                                    <span className="text-purple-600">●</span> Inquiry Received & Structured
                                </div>
                            </div>
                          </div>

                            {/* Action Triggers depending on stage */}
                            {stage === 'Inquiry' && (
                              <button
                                onClick={() => handleAdvanceStage(deal.id, 'Quote Sent')}
                                className="w-full py-1.5 rounded-lg bg-purple-600/20 hover:bg-purple-600/40 border border-purple-500/40 text-purple-600 text-[9px] font-space lowercase tracking-wider lowercase font-bold flex items-center justify-center gap-1.5 cursor-pointer"
                              >
                                <span>GENERATE PROPOSAL</span>
                                <ChevronRight className="w-3 h-3" />
                              </button>
                            )}

                            {stage === 'Quote Sent' && (
                              <button
                                onClick={() => handleAdvanceStage(deal.id, 'Proposal Viewed')}
                                className="w-full py-1.5 rounded-lg bg-amber-500/20 hover:bg-amber-500/40 border border-amber-500/40 text-amber-300 text-[9px] font-space lowercase tracking-wider lowercase font-bold flex items-center justify-center gap-1.5 cursor-pointer"
                              >
                                <span>MARK VIEWED BY CLIENT</span>
                                <ChevronRight className="w-3 h-3" />
                              </button>
                            )}

                            {stage === 'Proposal Viewed' && (
                              <button
                                onClick={() => handleAdvanceStage(deal.id, 'Contract Signed')}
                                className="w-full py-1.5 rounded-lg bg-emerald-500/20 hover:bg-emerald-500/40 border border-emerald-500/40 text-emerald-300 text-[9px] font-space lowercase tracking-wider lowercase font-bold flex items-center justify-center gap-1.5 cursor-pointer"
                              >
                                <span>CLIENT SIGNED CHARTER</span>
                                <ChevronRight className="w-3 h-3" />
                              </button>
                            )}

                            {stage === 'Contract Signed' && (
                              <button
                                onClick={() => {
                                  handleAdvanceStage(deal.id, 'Commission Settled');
                                  if (onIssueLiveCodeRequest) {
                                    onIssueLiveCodeRequest(deal.missionCode || '15D-001');
                                  }
                                }}
                                className="w-full py-1.5 rounded-lg bg-emerald-500 hover:bg-emerald-600 text-black text-[9px] font-space lowercase tracking-wider lowercase font-bold flex items-center justify-center gap-1.5 cursor-pointer shadow-lg"
                              >
                                <Zap className="w-3 h-3" />
                                <span>ISSUE LIVE BOOKING CODE</span>
                              </button>
                            )}

                            {/* Direct Handshake Bridge to VIP Portal */}
                            {deal.missionCode && (
                              <button
                                onClick={() => {
                                  if (onLaunchVipSession) {
                                    onLaunchVipSession(deal.missionCode!);
                                  } else {
                                    window.open(`https://vip.15dwings.com.ng/verify/${deal.missionCode}`, '_blank');
                                  }
                                }}
                                className="w-full py-1.5 rounded-lg bg-purple-100 hover:bg-white/20 text-gray-900 border border-purple-200 text-[9px] font-space lowercase tracking-wider lowercase font-semibold flex items-center justify-center gap-1.5 cursor-pointer"
                              >
                                <ExternalLink className="w-3 h-3 text-purple-600" />
                                <span>VIP CLIENT HANDOFF</span>
                              </button>
                            )}
                          </div>
                        </div>
                      ))
                    )}
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* SUB-TAB 2: HNWI & CORPORATE CLIENT PROFILES */}
      {activeSubTab === 'clients' && (
        <div className="space-y-6">
          <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 p-4 rounded-2xl border border-purple-200 bg-white/80 backdrop-blur-md backdrop-blur-[10px]">
            <div className="relative flex-1 max-w-md">
              <Search className="w-4 h-4 text-gray-600 absolute left-3.5 top-3" />
              <input
                type="text"
                placeholder="Search HNWI client name, company or email..."
                value={clientSearch}
                onChange={e => setClientSearch(e.target.value)}
                className="w-full pl-10 pr-4 py-2 bg-purple-50 border border-purple-200 rounded-xl text-xs text-gray-900 placeholder-gray-500 focus:outline-none focus:border-purple-500 transition-all"
              />
            </div>
            <div className="text-xs text-gray-600 font-mono">
              Showing <span className="text-gray-900 font-bold">{filteredClients.length}</span> verified profiles
            </div>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            {/* Client List */}
            <div className="lg:col-span-1 space-y-3">
              {filteredClients.map(client => (
                <div
                  key={client.id}
                  onClick={() => setSelectedClient(client)}
                  className={`p-4 rounded-2xl border transition-all cursor-pointer space-y-2 text-left ${
                    selectedClient?.id === client.id
                      ? 'border-purple-500 bg-purple-100 shadow-[0_0_20px_rgba(24,119,242,0.2)]'
                      : 'border-purple-200 bg-white/80 backdrop-blur-md hover:border-purple-300 hover:bg-purple-50'
                  }`}
                >
                  <div className="flex justify-between items-start">
                    <div>
                      <h3 className="font-space lowercase lowercase text-sm font-bold text-gray-900">
                        {client.fullName}
                      </h3>
                      <p className="text-[10px] text-gray-600 font-mono pt-0.5">
                        {client.company}
                      </p>
                    </div>
                    <span className="px-2.5 py-1 rounded-full bg-purple-100 text-purple-600 text-[9px] font-space lowercase font-bold lowercase tracking-wider">
                      {client.type}
                    </span>
                  </div>

                  <div className="grid grid-cols-2 gap-2 pt-2 text-[10px] border-t border-purple-200 font-mono">
                    <div>
                      <span className="text-gray-600 block">Total Charters:</span>
                      <span className="text-gray-900 font-bold">{client.totalFlightsBooked} flights</span>
                    </div>
                    <div>
                      <span className="text-gray-600 block">Lifetime Value:</span>
                      <span className="text-emerald-400 font-bold">{formatCurrency(client.totalLifetimeSpendUsd, 'USD')}</span>
                    </div>
                  </div>
                </div>
              ))}
            </div>

            {/* Client Profile Deep View */}
            <div className="lg:col-span-2 p-6 rounded-2xl border border-purple-200 bg-white/80 backdrop-blur-md backdrop-blur-[10px] space-y-6 text-left">
              {selectedClient ? (
                <div className="space-y-6">
                  {/* Header */}
                  <div className="flex justify-between items-start pb-4 border-b border-purple-200">
                    <div>
                      <div className="flex items-center gap-3">
                        <h2 className="font-space lowercase lowercase text-xl font-bold text-gray-900">
                          {selectedClient.fullName}
                        </h2>
                        <span className="px-3 py-1 rounded-full bg-purple-600/20 border border-purple-500/40 text-purple-600 text-[10px] font-space lowercase font-bold lowercase">
                          {selectedClient.type}
                        </span>
                      </div>
                      <p className="text-xs text-gray-600 font-mono pt-1">
                        {selectedClient.company} • Managed by {selectedClient.assignedBroker}
                      </p>
                    </div>

                    <button
                      onClick={() =>
                        handleCopyText(
                          `${selectedClient.fullName} - ${selectedClient.email}`,
                          'Client contact copied!'
                        )
                      }
                      className="p-2 bg-purple-100 hover:bg-white/20 text-gray-900 rounded-xl text-xs flex items-center gap-1.5 cursor-pointer"
                    >
                      <Copy className="w-3.5 h-3.5" />
                      <span>COPY CONTACT</span>
                    </button>
                  </div>

                  {/* Contact Info Grid */}
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div className="p-3.5 rounded-xl bg-purple-50 border border-purple-200 space-y-1">
                      <span className="text-[10px] text-gray-600 lowercase font-space lowercase block">EMAIL ADDRESS</span>
                      <span className="text-xs text-gray-900 font-mono">{selectedClient.email}</span>
                    </div>

                    <div className="p-3.5 rounded-xl bg-purple-50 border border-purple-200 space-y-1">
                      <span className="text-[10px] text-gray-600 lowercase font-space lowercase block">PHONE NUMBER</span>
                      <span className="text-xs text-gray-900 font-mono">{selectedClient.phone}</span>
                    </div>
                  </div>

                  {/* Private Aviation Preferences */}
                  <div className="space-y-3">
                    <h3 className="font-space lowercase text-xs font-bold text-purple-600 tracking-widest lowercase flex items-center gap-2">
                      <Plane className="w-4 h-4" />
                      <span>PRIVATE AVIATION PREFERENCES</span>
                    </h3>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs font-mono">
                      <div className="p-3 rounded-xl bg-purple-50 border border-purple-200 space-y-1">
                        <span className="text-gray-600 block text-[10px]">PREFERRED AIRCRAFT</span>
                        <span className="text-gray-900 font-semibold">{selectedClient.preferredAircraftClass}</span>
                      </div>

                      <div className="p-3 rounded-xl bg-purple-50 border border-purple-200 space-y-1">
                        <span className="text-gray-600 block text-[10px]">TAIL AVOIDANCES</span>
                        <span className="text-amber-300 font-semibold">
                          {selectedClient.tailAvoidances.join(', ') || 'None'}
                        </span>
                      </div>

                      <div className="p-3 rounded-xl bg-purple-50 border border-purple-200 space-y-1">
                        <span className="text-gray-600 block text-[10px]">CATERING & DIETARY</span>
                        <span className="text-emerald-300 font-semibold">
                          {selectedClient.dietaryRestrictions.join(', ') || 'Standard Executive Catering'}
                        </span>
                      </div>

                      <div className="p-3 rounded-xl bg-purple-50 border border-purple-200 space-y-1">
                        <span className="text-gray-600 block text-[10px]">PET POLICY</span>
                        <span className="text-gray-900 font-semibold">{selectedClient.petPolicy}</span>
                      </div>

                      <div className="p-3 rounded-xl bg-purple-50 border border-purple-200 col-span-2 space-y-1">
                        <span className="text-gray-600 block text-[10px]">SECURITY & ESCORT DETAIL</span>
                        <span className="text-gray-900 font-semibold">{selectedClient.securityDetails}</span>
                      </div>
                    </div>
                  </div>

                  {/* Passport & ID Vault */}
                  <div className="space-y-3 pt-2 border-t border-purple-200">
                    <div className="flex justify-between items-center">
                      <h3 className="font-space lowercase text-xs font-bold text-purple-600 tracking-widest lowercase flex items-center gap-2">
                        <ShieldCheck className="w-4 h-4" />
                        <span>PASSPORT & PASSENGER VAULT</span>
                      </h3>
                      <button
                        onClick={() =>
                          handleCopyText(
                            JSON.stringify(selectedClient.passportVault, null, 2),
                            'Passport vault exported!'
                          )
                        }
                        className="px-3 py-1 bg-purple-600/20 hover:bg-purple-600/40 text-purple-600 rounded-lg text-[10px] font-space lowercase font-bold lowercase cursor-pointer"
                      >
                        EXPORT FOR MANIFEST
                      </button>
                    </div>

                    <div className="space-y-2">
                      {selectedClient.passportVault.map(pass => (
                        <div
                          key={pass.id}
                          className="p-3 rounded-xl bg-purple-50 border border-purple-200 flex justify-between items-center text-xs font-mono"
                        >
                          <div>
                            <span className="text-gray-900 font-bold block">{pass.passengerName}</span>
                            <span className="text-gray-600 text-[10px]">
                              Passport #: {pass.passportNumber} • {pass.nationality}
                            </span>
                          </div>
                          <div className="text-right">
                            <span
                              className={`px-2.5 py-0.5 rounded-full text-[9px] font-bold lowercase ${
                                pass.status === 'Valid'
                                  ? 'bg-emerald-500/20 text-emerald-300'
                                  : 'bg-amber-500/20 text-amber-300'
                              }`}
                            >
                              {pass.status}
                            </span>
                            <span className="text-gray-600 text-[10px] block pt-1">
                              Exp: {pass.expiryDate}
                            </span>
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                </div>
              ) : (
                <div className="py-20 text-center space-y-3 text-gray-500">
                  <Users className="w-10 h-10 mx-auto text-gray-600" />
                  <p className="font-space lowercase text-xs tracking-widest lowercase">
                    SELECT A CLIENT FROM THE DIRECTORY TO VIEW DETAILED PROFILE & PASSPORT VAULT
                  </p>
                </div>
              )}
            </div>
          </div>
        </div>
      )}

      {/* SUB-TAB 3: WHITE-LABEL PROPOSAL BUILDER */}
      {activeSubTab === 'proposals' && (
        <WhiteLabelProposalBuilder
          missionId="15D-7F9E"
          originCode="LOS"
          destCode="EGKB"
          aircraftName="Challenger 650 (5N-ZNT)"
          baselineWholesaleCostUsd={110000}
        />
      )}

      {/* SUB-TAB 4: TRIP HISTORY & LOGS */}
      {activeSubTab === 'history' && (
        <div className="space-y-4 p-6 rounded-2xl border border-purple-200 bg-white/80 backdrop-blur-md backdrop-blur-[10px]">
          <div className="flex justify-between items-center pb-4 border-b border-purple-200">
            <div>
              <h3 className="font-space lowercase text-base font-bold text-gray-900 lowercase tracking-wider">
                HISTORICAL TRIP LEDGER & CHARTER LOGS
              </h3>
              <p className="text-xs text-gray-600">
                Complete flight activity, wholesale settlement costs, and broker margin historical record.
              </p>
            </div>
          </div>

          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs font-mono">
              <thead>
                <tr className="border-b border-purple-200 text-gray-600 text-[10px] font-space lowercase lowercase">
                  <th className="py-3 px-2">BOOKING CODE</th>
                  <th className="py-3 px-2">CLIENT</th>
                  <th className="py-3 px-2">DATE</th>
                  <th className="py-3 px-2">ROUTE</th>
                  <th className="py-3 px-2">AIRCRAFT & TAIL</th>
                  <th className="py-3 px-2">WHOLESALE COST</th>
                  <th className="py-3 px-2">BROKER PROFIT</th>
                  <th className="py-3 px-2">PAYMENT RAIL</th>
                  <th className="py-3 px-2">STATUS</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-white/10">
                {INITIAL_FLIGHT_HISTORY.map(flight => (
                  <tr key={flight.id} className="hover:bg-purple-50 transition-colors">
                    <td className="py-3 px-2 font-bold text-purple-600">{flight.missionCode}</td>
                    <td className="py-3 px-2 text-gray-900">{flight.clientName}</td>
                    <td className="py-3 px-2 text-gray-600">{flight.flightDate}</td>
                    <td className="py-3 px-2 text-gray-900 font-bold">{flight.route}</td>
                    <td className="py-3 px-2 text-gray-700">{flight.aircraftModel}</td>
                    <td className="py-3 px-2 text-gray-700">{formatCurrency(flight.wholesaleCostUsd, 'USD')}</td>
                    <td className="py-3 px-2 text-emerald-400 font-bold">
                      +{formatCurrency(flight.brokerProfitUsd, 'USD')}
                    </td>
                    <td className="py-3 px-2 text-purple-600 text-[10px]">{flight.paymentRail}</td>
                    <td className="py-3 px-2">
                      <span className="px-2 py-0.5 rounded-full bg-emerald-500/20 text-emerald-300 text-[9px] font-bold lowercase">
                        {flight.status}
                      </span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* SUB-TAB 5: REVENUE ANALYTICS */}
      {activeSubTab === 'analytics' && (
        <div className="space-y-6">
          <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
            <div className="p-5 rounded-2xl border border-purple-200 bg-white/80 backdrop-blur-md space-y-2">
              <span className="text-[10px] text-gray-600 font-space lowercase lowercase tracking-widest block">
                TOTAL CLOSED CHARTER VOLUME
              </span>
              <p className="text-2xl font-space lowercase lowercase font-bold text-gray-900 font-mono">
                {formatCurrency(totalClosedVolume || 1850000, 'USD')}
              </p>
              <span className="text-[10px] text-emerald-400 font-mono">↑ +24% vs last quarter</span>
            </div>

            <div className="p-5 rounded-2xl border border-purple-200 bg-white/80 backdrop-blur-md space-y-2">
              <span className="text-[10px] text-gray-600 font-space lowercase lowercase tracking-widest block">
                NET BROKER COMFLIGHTS
              </span>
              <p className="text-2xl font-space lowercase lowercase font-bold text-purple-600 font-mono">
                {formatCurrency(totalCommissions || 248500, 'USD')}
              </p>
              <span className="text-[10px] text-purple-600 font-mono">Average margin: 13.4%</span>
            </div>

            <div className="p-5 rounded-2xl border border-purple-200 bg-white/80 backdrop-blur-md space-y-2">
              <span className="text-[10px] text-gray-600 font-space lowercase lowercase tracking-widest block">
                PROVIDUS NGN CLEARING RAIL
              </span>
              <p className="text-2xl font-space lowercase lowercase font-bold text-emerald-400 font-mono">
                ₦382,400,000
              </p>
              <span className="text-[10px] text-gray-600 font-mono">Sub-second NUBAN settlement</span>
            </div>

            <div className="p-5 rounded-2xl border border-purple-200 bg-white/80 backdrop-blur-md space-y-2">
              <span className="text-[10px] text-gray-600 font-space lowercase lowercase tracking-widest block">
                USDC ESCROW (SOLANA / BASE L2)
              </span>
              <p className="text-2xl font-space lowercase lowercase font-bold text-indigo-400 font-mono">
                $189,750 USDC
              </p>
              <span className="text-[10px] text-indigo-300 font-mono">Fireblocks Vault Locked</span>
            </div>
          </div>
        </div>
      )}

      {/* SUB-TAB 6: MESSAGING */}
      {activeSubTab === 'messaging' && (
        <div className="p-6 rounded-2xl border border-purple-200 bg-white/80 backdrop-blur-md backdrop-blur-[10px] space-y-4 max-w-3xl mx-auto">
          <div className="pb-3 border-b border-purple-200 flex justify-between items-center">
            <div>
              <h3 className="font-space lowercase text-sm font-bold text-gray-900 lowercase">
                CLIENT CONCIERGE CHAT HUB
              </h3>
              <p className="text-[10px] text-gray-600 font-mono">
                Direct client interaction vault without exposing platform backend details.
              </p>
            </div>
            <span className="px-2.5 py-1 rounded-full bg-emerald-500/20 text-emerald-300 text-[9px] font-mono font-bold">
              ● Client Online
            </span>
          </div>

          <div className="space-y-3 min-h-[280px] max-h-[400px] overflow-y-auto pr-2">
            {chatMessages.map(msg => (
              <div
                key={msg.id}
                className={`flex flex-col ${msg.isClient ? 'items-start' : 'items-end'}`}
              >
                <div
                  className={`p-3 rounded-2xl max-w-md text-xs font-mono space-y-1 ${
                    msg.isClient
                      ? 'bg-purple-100 text-gray-900 rounded-tl-none'
                      : 'bg-purple-600 text-gray-900 rounded-tr-none'
                  }`}
                >
                  <span className="text-[9px] opacity-75 block font-space lowercase lowercase">{msg.sender}</span>
                  <p>{msg.text}</p>
                  <span className="text-[8px] opacity-60 text-right block pt-1">{msg.time}</span>
                </div>
              </div>
            ))}
          </div>

          <form onSubmit={handleSendMessage} className="flex gap-2 pt-2 border-t border-purple-200">
            <input
              type="text"
              placeholder="Type client concierge message..."
              value={newMessageInput}
              onChange={e => setNewMessageInput(e.target.value)}
              className="flex-1 px-4 py-2.5 bg-purple-50 border border-purple-200 rounded-xl text-xs text-gray-900 focus:outline-none focus:border-purple-500"
            />
            <button
              type="submit"
              className="px-4 py-2.5 bg-purple-600 hover:bg-purple-600/90 text-gray-900 rounded-xl text-xs font-space lowercase font-bold lowercase cursor-pointer"
            >
              SEND
            </button>
          </form>
        </div>
      )}

      {/* SUB-TAB 7: TASKS & ALERTS */}
      {activeSubTab === 'tasks' && (
        <div className="p-6 rounded-2xl border border-purple-200 bg-white/80 backdrop-blur-md backdrop-blur-[10px] space-y-6">
          <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 pb-4 border-b border-purple-200">
            <div>
              <h3 className="font-space lowercase text-base font-bold text-gray-900 lowercase tracking-wider">
                AUTOMATED REMINDERS & TASK ENGINE
              </h3>
              <p className="text-xs text-gray-600">
                Auto-generated alerts for 48h quote follow-ups, passport expirations, and annual trip prep.
              </p>
            </div>

            <form onSubmit={handleAddTask} className="flex gap-2">
              <input
                type="text"
                placeholder="New broker task..."
                value={newTaskTitle}
                onChange={e => setNewTaskTitle(e.target.value)}
                className="px-3.5 py-2 bg-purple-50 border border-purple-200 rounded-xl text-xs text-gray-900 placeholder-gray-500 focus:outline-none focus:border-purple-500"
              />
              <button
                type="submit"
                className="px-4 py-2 bg-purple-600 hover:bg-purple-600/90 text-gray-900 rounded-xl text-xs font-space lowercase font-bold lowercase cursor-pointer"
              >
                ADD TASK
              </button>
            </form>
          </div>

          <div className="space-y-2">
            {tasks.map(task => (
              <div
                key={task.id}
                className="p-3.5 rounded-xl border border-purple-200 bg-purple-50 flex items-center justify-between text-xs font-mono"
              >
                <div className="flex items-center gap-3">
                  <input
                    type="checkbox"
                    checked={task.completed}
                    onChange={() =>
                      setTasks(prev =>
                        prev.map(t => (t.id === task.id ? { ...t, completed: !t.completed } : t))
                      )
                    }
                    className="w-4 h-4 rounded bg-white border-purple-300 text-purple-600 focus:ring-0 cursor-pointer"
                  />
                  <div>
                    <span
                      className={`font-semibold text-gray-900 ${
                        task.completed ? 'line-through text-gray-500' : ''
                      }`}
                    >
                      {task.title}
                    </span>
                    {task.clientName && (
                      <span className="text-[10px] text-gray-600 block pt-0.5">
                        Client: {task.clientName}
                      </span>
                    )}
                  </div>
                </div>

                <div className="flex items-center gap-2">
                  <span
                    className={`px-2 py-0.5 rounded text-[9px] font-bold lowercase ${
                      task.priority === 'High'
                        ? 'bg-red-500/20 text-red-300'
                        : 'bg-purple-600/20 text-purple-600'
                    }`}
                  >
                    {task.priority}
                  </span>
                  <span className="text-[10px] text-gray-600">{task.dueDate}</span>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* SUB-TAB 8: FLEET DIRECTORY */}
      {activeSubTab === 'directory' && (
        <div className="p-6 rounded-2xl border border-purple-200 bg-white/80 backdrop-blur-md backdrop-blur-[10px] space-y-4">
          <div className="pb-4 border-b border-purple-200">
            <h3 className="font-space lowercase text-base font-bold text-gray-900 lowercase tracking-wider">
              VERIFIED FLEET DIRECTORY (READ-ONLY)
            </h3>
            <p className="text-xs text-gray-600">
              Live aircraft availability and hourly wholesale rates for instant quote calculation.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
            {INITIAL_AIRCRAFT_DIRECTORY.map(air => (
              <div
                key={air.id}
                className="p-4 rounded-xl border border-purple-200 bg-purple-50 space-y-3 text-left"
              >
                <div className="flex justify-between items-start">
                  <div>
                    <span className="px-2 py-0.5 rounded bg-purple-600/20 text-purple-600 text-[9px] font-mono font-bold">
                      {air.tailNumber}
                    </span>
                    <h4 className="font-space lowercase lowercase text-sm font-bold text-gray-900 pt-1">{air.model}</h4>
                  </div>
                  <span className="text-[9px] text-emerald-400 font-mono font-bold">
                    {air.argusRating}
                  </span>
                </div>

                <div className="space-y-1 text-xs font-mono text-gray-700">
                  <div className="flex justify-between">
                    <span className="text-gray-600">Category:</span>
                    <span>{air.category}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-gray-600">Base Airport:</span>
                    <span className="text-gray-900">{air.baseAirport.split(' ')[0]}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-gray-600">Rate:</span>
                    <span className="text-emerald-400 font-bold">
                      {formatCurrency(air.hourlyRateUsd, 'USD')}/hr
                    </span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-gray-600">Operator:</span>
                    <span className="text-purple-600">{air.operatorName}</span>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* SUB-TAB 9: TEAM ACCOUNTS */}
      {activeSubTab === 'team' && (
        <div className="p-6 rounded-2xl border border-purple-200 bg-white/80 backdrop-blur-md backdrop-blur-[10px] space-y-4">
          <div className="pb-4 border-b border-purple-200 flex justify-between items-center">
            <div>
              <h3 className="font-space lowercase text-base font-bold text-gray-900 lowercase tracking-wider">
                BROKERAGE TEAM SUB-ACCOUNTS
              </h3>
              <p className="text-xs text-gray-600">
                Manage junior brokers, lead assignments, and commission split ratios.
              </p>
            </div>
            <button className="px-3.5 py-2 bg-purple-600 hover:bg-purple-600/90 text-gray-900 rounded-xl text-xs font-space lowercase font-bold lowercase cursor-pointer">
              INVITE BROKER
            </button>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            {INITIAL_TEAM_MEMBERS.map(member => (
              <div
                key={member.id}
                className="p-4 rounded-xl border border-purple-200 bg-purple-50 space-y-3 text-left"
              >
                <div className="flex justify-between items-start">
                  <div>
                    <h4 className="font-space lowercase lowercase text-sm font-bold text-gray-900">{member.fullName}</h4>
                    <span className="text-[10px] text-purple-600 font-mono">{member.role}</span>
                  </div>
                  <span className="px-2 py-0.5 rounded bg-emerald-500/20 text-emerald-300 text-[9px] font-mono font-bold">
                    {member.commissionSplitPercent}% Split
                  </span>
                </div>

                <div className="space-y-1 text-xs font-mono text-gray-700 pt-2 border-t border-purple-200">
                  <div className="flex justify-between">
                    <span className="text-gray-600">Email:</span>
                    <span>{member.email}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-gray-600">Active Deals:</span>
                    <span className="text-gray-900 font-bold">{member.assignedDealsCount}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-gray-600">Closed Volume:</span>
                    <span className="text-emerald-400 font-bold">
                      {formatCurrency(member.closedVolumeUsd, 'USD')}
                    </span>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* MODAL: ADD CLIENT */}
      <AnimatePresence>
        {showAddClientModal && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-50 bg-white/80 backdrop-blur-md backdrop-blur-[10px] flex items-center justify-center p-4"
          >
            <div className="w-full max-w-md p-6 rounded-2xl border border-purple-300 bg-white space-y-4 text-left">
              <div className="flex justify-between items-center pb-2 border-b border-purple-200">
                <h3 className="font-space lowercase text-sm font-bold text-gray-900 lowercase">
                  ADD NEW HNWI CLIENT PROFILE
                </h3>
                <button
                  onClick={() => setShowAddClientModal(false)}
                  className="p-1 text-gray-600 hover:text-gray-900"
                >
                  <X className="w-5 h-5" />
                </button>
              </div>

              <form onSubmit={handleCreateClient} className="space-y-3 text-xs">
                <div>
                  <label className="text-[10px] font-space lowercase text-gray-600 lowercase block mb-1">
                    FULL NAME
                  </label>
                  <input
                    type="text"
                    required
                    placeholder="e.g. Chief Alani Adeleke"
                    value={newClientName}
                    onChange={e => setNewClientName(e.target.value)}
                    className="w-full p-2.5 bg-purple-50 border border-purple-200 rounded-xl text-gray-900 focus:outline-none focus:border-purple-500"
                  />
                </div>

                <div>
                  <label className="text-[10px] font-space lowercase text-gray-600 lowercase block mb-1">
                    COMPANY / PRIVATE OFFICE
                  </label>
                  <input
                    type="text"
                    placeholder="e.g. Adeleke Holdings"
                    value={newClientCompany}
                    onChange={e => setNewClientCompany(e.target.value)}
                    className="w-full p-2.5 bg-purple-50 border border-purple-200 rounded-xl text-gray-900 focus:outline-none focus:border-purple-500"
                  />
                </div>

                <div>
                  <label className="text-[10px] font-space lowercase text-gray-600 lowercase block mb-1">
                    EMAIL ADDRESS
                  </label>
                  <input
                    type="email"
                    placeholder="client@privateoffice.com"
                    value={newClientEmail}
                    onChange={e => setNewClientEmail(e.target.value)}
                    className="w-full p-2.5 bg-purple-50 border border-purple-200 rounded-xl text-gray-900 focus:outline-none focus:border-purple-500"
                  />
                </div>

                <div>
                  <label className="text-[10px] font-space lowercase text-gray-600 lowercase block mb-1">
                    PHONE NUMBER
                  </label>
                  <input
                    type="text"
                    placeholder="+234 803 000 0000"
                    value={newClientPhone}
                    onChange={e => setNewClientPhone(e.target.value)}
                    className="w-full p-2.5 bg-purple-50 border border-purple-200 rounded-xl text-gray-900 focus:outline-none focus:border-purple-500"
                  />
                </div>

                <div>
                  <label className="text-[10px] font-space lowercase text-gray-600 lowercase block mb-1">
                    CLIENT TYPE
                  </label>
                  <select
                    value={newClientType}
                    onChange={e => setNewClientType(e.target.value as any)}
                    className="w-full p-2.5 bg-white border border-purple-200 rounded-xl text-gray-900 focus:outline-none focus:border-purple-500"
                  >
                    <option value="HNWI">HNWI Individual</option>
                    <option value="Corporate">Corporate Fleet</option>
                    <option value="Family Office">Family Office</option>
                    <option value="VIP Royal">Royal / Head of State</option>
                  </select>
                </div>

                <div className="pt-2 flex gap-2">
                  <button
                    type="submit"
                    className="flex-1 py-3 bg-purple-600 hover:bg-purple-600/90 text-gray-900 rounded-xl font-space lowercase text-xs font-bold lowercase cursor-pointer"
                  >
                    SAVE PROFILE
                  </button>
                  <button
                    type="button"
                    onClick={() => setShowAddClientModal(false)}
                    className="py-3 px-4 bg-purple-100 hover:bg-white/20 text-gray-900 rounded-xl font-space lowercase text-xs font-bold lowercase cursor-pointer"
                  >
                    CANCEL
                  </button>
                </div>
              </form>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* MODAL: ADD DEAL */}
      <AnimatePresence>
        {showAddDealModal && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-50 bg-white/80 backdrop-blur-md backdrop-blur-[10px] flex items-center justify-center p-4"
          >
            <div className="w-full max-w-md p-6 rounded-2xl border border-purple-300 bg-white space-y-4 text-left">
              <div className="flex justify-between items-center pb-2 border-b border-purple-200">
                <h3 className="font-space lowercase text-sm font-bold text-gray-900 lowercase">
                  NEW CHARTER DEAL INQUIRY
                </h3>
                <button
                  onClick={() => setShowAddDealModal(false)}
                  className="p-1 text-gray-600 hover:text-gray-900"
                >
                  <X className="w-5 h-5" />
                </button>
              </div>

              <form onSubmit={handleCreateDeal} className="space-y-3 text-xs">
                <div>
                  <label className="text-[10px] font-space lowercase text-gray-600 lowercase block mb-1">
                    SELECT CLIENT
                  </label>
                  <select
                    value={newDealClient}
                    onChange={e => setNewDealClient(e.target.value)}
                    className="w-full p-2.5 bg-white border border-purple-200 rounded-xl text-gray-900 focus:outline-none focus:border-purple-500"
                  >
                    {clients.map(c => (
                      <option key={c.id} value={c.id}>
                        {c.fullName} ({c.company})
                      </option>
                    ))}
                  </select>
                </div>

                <div className="grid grid-cols-2 gap-2">
                  <div>
                    <label className="text-[10px] font-space lowercase text-gray-600 lowercase block mb-1">
                      ORIGIN (ICAO/IATA)
                    </label>
                    <input
                      type="text"
                      required
                      value={newDealOrigin}
                      onChange={e => setNewDealOrigin(e.target.value.toUpperCase())}
                      className="w-full p-2.5 bg-purple-50 border border-purple-200 rounded-xl text-gray-900 focus:outline-none focus:border-purple-500 font-mono"
                    />
                  </div>
                  <div>
                    <label className="text-[10px] font-space lowercase text-gray-600 lowercase block mb-1">
                      DESTINATION
                    </label>
                    <input
                      type="text"
                      required
                      value={newDealDest}
                      onChange={e => setNewDealDest(e.target.value.toUpperCase())}
                      className="w-full p-2.5 bg-purple-50 border border-purple-200 rounded-xl text-gray-900 focus:outline-none focus:border-purple-500 font-mono"
                    />
                  </div>
                </div>

                <div>
                  <label className="text-[10px] font-space lowercase text-gray-600 lowercase block mb-1">
                    AIRCRAFT CATEGORY
                  </label>
                  <select
                    value={newDealAircraft}
                    onChange={e => setNewDealAircraft(e.target.value)}
                    className="w-full p-2.5 bg-white border border-purple-200 rounded-xl text-gray-900 focus:outline-none focus:border-purple-500"
                  >
                    <option value="Heavy Jet (Challenger 650)">Heavy Jet (Challenger 650)</option>
                    <option value="Ultra Long Range (G650ER)">Ultra Long Range (G650ER)</option>
                    <option value="Super Midsize (Hawker 900XP)">Super Midsize (Hawker 900XP)</option>
                    <option value="Light Jet (Citation CJ4)">Light Jet (Citation CJ4)</option>
                  </select>
                </div>

                <div>
                  <label className="text-[10px] font-space lowercase text-gray-600 lowercase block mb-1">
                    ESTIMATED WHOLESALE COST (USD)
                  </label>
                  <input
                    type="number"
                    required
                    value={newDealCost}
                    onChange={e => setNewDealCost(Number(e.target.value))}
                    className="w-full p-2.5 bg-purple-50 border border-purple-200 rounded-xl text-gray-900 focus:outline-none focus:border-purple-500 font-mono"
                  />
                </div>

                <div className="pt-2 flex gap-2">
                  <button
                    type="submit"
                    className="flex-1 py-3 bg-purple-600 hover:bg-purple-600/90 text-gray-900 rounded-xl font-space lowercase text-xs font-bold lowercase cursor-pointer"
                  >
                    CREATE DEAL IN PIPELINE
                  </button>
                  <button
                    type="button"
                    onClick={() => setShowAddDealModal(false)}
                    className="py-3 px-4 bg-purple-100 hover:bg-white/20 text-gray-900 rounded-xl font-space lowercase text-xs font-bold lowercase cursor-pointer"
                  >
                    CANCEL
                  </button>
                </div>
              </form>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
};
